baseURL = "https://fdyfox.com/"
languageCode = "de-de"
language = "de-de"
defaultContentLanguage = "de-de"
title = "FdyFox"
theme = "PaperMod"
enableRobotsTXT = true
paginate = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.footer]
  text = "[Impressum](/impressum/) · [Datenschutz](/datenschutz/)"

[params]
  author = "Ferdy"
  description = "Notizen, Gedanken und Kram"
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = false

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false
  linkFullImages = true

[params.homeInfoParams]
  Title = ""
  Content = '''<pre class="home-ascii">  __     _        __
 / _| __| |_   _ / _| _____  __
| |_ / _` | | | | |_ / _ \ \/ /
|  _| (_| | |_| |  _| (_) >  <
|_|  \__,_|\__, |_|  \___/_/\_\
           |___/</pre>

Notizen, Gedanken und Kram.'''

[[params.socialIcons]]
  name = "email"
  url = "mailto:ferdy@fdyfox.com"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/FdyFox"

[[params.socialIcons]]
  name = "telegram"
  url = "https://t.me/brazier85"

[[params.socialIcons]]
  name = "signal"
  url = "https://signal.me/#eu/E5WqkEwvgEPOcT0rofLpNThsJ72WBqw7qnQ-G7aqz9slVXpsQFhJSpUWiv0q6pVK"

[menu]
  [[menu.main]]
    name = "~/Logbuch"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "~/Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "~/Suche"
    url = "/search/"
    weight = 3
  [[menu.main]]
    name = "~/About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "~/Kontakt"
    url = "/kontakt/"
    weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.extensions.extras.alerts]
  enable = true

[markup.highlight]
  noClasses = false
